FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04

# Prevents Python from writing .pyc files
# Ensures Python output is not buffered
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_COMPILE_BYTECODE=0 \
    UV_LINK_MODE=copy \
    UV_SYSTEM_PYTHON=1

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-dev \
        python3-pip \
        python3-venv \
        python-is-python3 \
        build-essential \
        cmake \
        curl \
        git \
        libffi-dev \
        libssl-dev \
        libgl1 \
        libsm6 \
        libxrender1 \
        libxext6 \
        libglib2.0-0 \
        zstd \
        && rm -rf /var/lib/apt/lists/* \
        && rm -f /usr/lib/python*/EXTERNALLY-MANAGED

WORKDIR /workspace

# Copy torchsig
COPY . .

# Replace opencv-python with opencv-python-headless
RUN sed -i 's/opencv-python/opencv-python-headless/g' pyproject.toml

# Install Python dependencies
# Increase file descriptor limit to prevent "Too many open files" errors
RUN ulimit -n 65536 && \
    pip install --no-cache-dir uv && \
    uv pip install --system --no-cache -e .

CMD ["bash"]